apiVersion: v1
kind: ServiceAccount
metadata:
  name: isaaclab-gpu
  namespace: wbc-training
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wbc-training-isaaclab-gpu-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:openshift:scc:anyuid"
subjects:
  - kind: ServiceAccount
    name: isaaclab-gpu
    namespace: wbc-training
