apiVersion: v1
kind: Secret
metadata:
  name: mlflow-s3-credentials
  namespace: redhat-ods-applications
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
---
apiVersion: mlflow.opendatahub.io/v1
kind: MLflow
metadata:
  name: mlflow
spec:
  defaultArtifactRoot: "s3://mlflow/artifacts"
  serveArtifacts: true
  artifactsDestination: "s3://mlflow/artifacts"
  env:
    - name: MLFLOW_S3_ENDPOINT_URL
      value: "http://minio.wbc-training.svc:9000"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: mlflow-s3-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: mlflow-s3-credentials
          key: AWS_SECRET_ACCESS_KEY
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
